# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

module(
    name = "strands",
    version = "0.1.0",
)

bazel_dep(name = "rules_java", version = "9.9.0")
bazel_dep(name = "rules_jvm_external", version = "7.1")
bazel_dep(name = "bazel_skylib", version = "1.9.2")

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    artifacts = [
        # Production dependencies
        "com.google.auto.service:auto-service:1.1.1",
        "com.google.flogger:flogger:0.9",
        "com.google.flogger:flogger-system-backend:0.9",
        "com.google.flogger:google-extensions:0.9",
        "com.google.guava:guava:33.7.1-jre",
        "org.jspecify:jspecify:1.0.1",
        # Compile-only dependencies
        "com.google.auto.service:auto-service-annotations:1.1.1",
        "com.google.errorprone:error_prone_annotations:2.50.0",
        # Test-only dependencies
        "com.google.guava:guava-testlib:33.7.1-jre",
        "com.google.truth:truth:1.4.5",
        "junit:junit:4.13.2",
        "org.mockito:mockito-core:5.23.0",
    ],
    known_contributing_modules = ["protobuf"],
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)
maven.amend_artifact(
    coordinates = "com.google.auto.service:auto-service-annotations",
    neverlink = "true",
)
maven.amend_artifact(
    coordinates = "com.google.errorprone:error_prone_annotations",
    neverlink = "true",
)
maven.amend_artifact(
    testonly = "true",
    coordinates = "com.google.guava:guava-testlib",
)
maven.amend_artifact(
    testonly = "true",
    coordinates = "com.google.truth:truth",
)
maven.amend_artifact(
    testonly = "true",
    coordinates = "junit:junit",
)
maven.amend_artifact(
    testonly = "true",
    coordinates = "org.mockito:mockito-core",
)
use_repo(maven, "maven")
