# Copyright 2026 The Strands Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_java//java:defs.bzl", "java_library", "java_test")
load("//:testing.bzl", "junit4_test_suites")

package(default_testonly = True)

java_library(
    name = "tests",
    srcs = glob(
        ["*.java"],
        exclude = [
            "ReflectionVirtualThreadTest.java",
            "UnsafeConcurrentExecutionTest.java",
        ],
    ),
    deps = [
        "//src/main/java/com/google/async/strands",
        "//src/main/java/com/google/async/strands:testing",
        "@maven//:com_google_errorprone_error_prone_annotations",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_guava_guava_testlib",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_mockito_mockito_core",
    ],
)

junit4_test_suites(
    name = "gen_tests",
    sizes = ["small"],
    src_dir = "src/test/java",
    deps = [":tests"],
)

java_test(
    name = "ReflectionVirtualThreadTest",
    size = "small",
    srcs = ["ReflectionVirtualThreadTest.java"],
    jvm_flags = ["--add-opens=java.base/java.lang=ALL-UNNAMED"],
    test_class = "com.google.async.strands.ReflectionVirtualThreadTest",
    deps = [
        "//src/main/java/com/google/async/strands",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "UnsafeConcurrentExecutionTest",
    size = "small",
    srcs = ["UnsafeConcurrentExecutionTest.java"],
    jvm_flags = ["-Dcom.google.async.strands.allowUnsafeConcurrentExecution=true"],
    test_class = "com.google.async.strands.UnsafeConcurrentExecutionTest",
    deps = [
        "//src/main/java/com/google/async/strands",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)
